//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rewards.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILE
    {
        public int ID { get; set; }
        public int FORM_ID { get; set; }
        public byte[] CONTENT { get; set; }
        public string FILE_NAME { get; set; }
        public string FILE_EXTENSION { get; set; }
    
        public virtual FORM FORM { get; set; }
    }
}
