//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rewards.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FORM()
        {
            this.FILE = new HashSet<FILE>();
        }
    
        public int ID { get; set; }
        public int USER_ID { get; set; }
        public int ACTIVITY_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public Nullable<System.DateTime> MANAGER_DATA_APROVED { get; set; }
    
        public virtual ACTIVITY ACTIVITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FILE> FILE { get; set; }
        public virtual USER USER { get; set; }
    }
}
