//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rewards.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PURCHASE
    {
        public int ID { get; set; }
        public int USER_ID { get; set; }
        public int REWARD_ID { get; set; }
        public System.DateTime PURCHASE_DATE { get; set; }
    
        public virtual USER USER { get; set; }
        public virtual REWARD REWARD { get; set; }
    }
}
