//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rewards.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class REWARD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REWARD()
        {
            this.PURCHASE = new HashSet<PURCHASE>();
            this.REWARD_STOCK = new HashSet<REWARD_STOCK>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public int PRICE { get; set; }
        public byte[] IMAGE { get; set; }
        public Nullable<bool> ACTIVATED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PURCHASE> PURCHASE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REWARD_STOCK> REWARD_STOCK { get; set; }
    }
}
